$out_dir = "build";

$tex_src .= "\\input{%S}";

$bibtex_use = 2;

$ENV{'BIBINPUTS'}='../tex';

$pdf_mode = 1;
$pdflatex = "texfot lualatex %O -interaction=nonstopmode -synctex=1 -shell-escape \"$tex_src\"";
